<?php

define( 'ROSLYN_NEWS_VERSION', '1.0.2' );
define( 'ROSLYN_NEWS_ABS_PATH', dirname( __FILE__ ) );
define( 'ROSLYN_NEWS_REL_PATH', dirname( plugin_basename( __FILE__ ) ) );
define( 'ROSLYN_NEWS_URL_PATH', plugin_dir_url( __FILE__ ) );
define( 'ROSLYN_NEWS_LIB_PATH', ROSLYN_NEWS_ABS_PATH . '/lib' );
define( 'ROSLYN_NEWS_LIB_URL_PATH', ROSLYN_NEWS_URL_PATH . 'lib' );
define( 'ROSLYN_NEWS_ASSETS_PATH', ROSLYN_NEWS_ABS_PATH . '/assets' );
define( 'ROSLYN_NEWS_ASSETS_URL_PATH', ROSLYN_NEWS_URL_PATH . 'assets' );
define( 'ROSLYN_NEWS_MODULES_PATH', ROSLYN_NEWS_ABS_PATH . '/modules' );
define( 'ROSLYN_NEWS_MODULES_URL_PATH', ROSLYN_NEWS_URL_PATH . 'modules' );
define( 'ROSLYN_NEWS_BLOG_PATH', ROSLYN_NEWS_MODULES_PATH . '/blog' );
define( 'ROSLYN_NEWS_BLOG_URL_PATH', ROSLYN_NEWS_MODULES_URL_PATH . 'blog' );
define( 'ROSLYN_NEWS_SHORTCODES_PATH', ROSLYN_NEWS_MODULES_PATH . '/shortcodes' );
define( 'ROSLYN_NEWS_SHORTCODES_URL_PATH', ROSLYN_NEWS_MODULES_URL_PATH . 'shortcodes' );
define( 'ROSLYN_NEWS_WIDGETS_PATH', ROSLYN_NEWS_MODULES_PATH . '/widgets' );
define( 'ROSLYN_NEWS_WIDGETS_URL_PATH', ROSLYN_NEWS_MODULES_URL_PATH . 'widgets' );
define( 'ROSLYN_NEWS_REVIEW_PATH', ROSLYN_NEWS_MODULES_PATH . '/review' );
define( 'ROSLYN_NEWS_REVIEW_URL_PATH', ROSLYN_NEWS_MODULES_URL_PATH . 'review' );